COMP: Fix VTK build failure when using Visual Studio 17.7.4
Visual Studio 17.7.4 was used when the following internal compiler error was observed:

2>C:\SP\SPR22b\vtk\ThirdParty\fmt\vtkfmt\vtkfmt/ostream.h(32,1): fatal error C1001: Internal compiler error. [C:\SP\SPR22b\vtk-bin\ThirdParty\ioss\vtkioss\ioss.vcxproj]